[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "MD_rigid"
authors = [{name = "Andrea Silva", email = "abc@def.com"}]
dynamic = ["version", "description"]
