[build-system]
requires = ["setuptools ~= 66.0.0", "cython ~= 0.29.35", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "MD_rigid"
version = "0.0.1"
description = "Statics and dynamics of 2D rigid cluster over a substrate. The degrees of freedom are the CM position and orientation."
authors = [{name = "Andrea Silva", email="ansilva@sissa.it"}]
readme = "README.md"
license = {file = "LICENSE.txt"}
dynamic = ["version", "description"]
requires-python = ">=3.10"
